# This file was generated by GoReleaser. DO NOT EDIT.
cask "melonite" do
  version "0.0.29"

  on_macos do
    on_arm do
      sha256 "f38a4b59a77d0cd341534bb216a94edc52524c3f6e7356d7cd1bee850447dc44"
      url "https://github.com/meloniteai/melonite-client/releases/download/v#{version}/melonite_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "507b8493375069a9c14839acb699bd151c341a33d08da36d9583949773978304"
      url "https://github.com/meloniteai/melonite-client/releases/download/v#{version}/melonite_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "590463b0cdc6cc90abacbfb75f64e7858357a5ad36182763e2269a72a3b80f09"
      url "https://github.com/meloniteai/melonite-client/releases/download/v#{version}/melonite_linux_arm64.tar.gz"
    end
  end

  name "melonite"
  desc "Melonite client: a headless MCP server for agent harnesses"
  homepage "https://melonite.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "melonite"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/melonite"]
    end
  end

  # No zap stanza required

end
