# This file was generated by GoReleaser. DO NOT EDIT.
cask "melonite" do
  version "0.0.24"

  on_macos do
    on_arm do
      sha256 "3171f53639a152a7bc2ff4d8b137942dcb4ba1847f66bf87864ca78da33f14b5"
      url "https://github.com/meloniteai/melonite-client/releases/download/v#{version}/melonite_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "76208deb90ea41e1cc5eb5665f7ca6bd5960dfcd206815d8f43748e9dd30fa72"
      url "https://github.com/meloniteai/melonite-client/releases/download/v#{version}/melonite_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "da03b7caaffa9ce2bc47596057e7e879e9176fe76d9dfd3ec57374f0c79aa8dc"
      url "https://github.com/meloniteai/melonite-client/releases/download/v#{version}/melonite_linux_arm64.tar.gz"
    end
  end

  name "melonite"
  desc "Melonite client: a headless MCP server for agent harnesses"
  homepage "https://melonite.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "melonite"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/melonite"]
    end
  end

  # No zap stanza required

end
