# This file was generated by GoReleaser. DO NOT EDIT.
cask "melonite" do
  version "0.1.18"

  on_macos do
    on_arm do
      sha256 "170706c9634730889c5a8c4056e3c6dd55035d752adf8b7c19e4256f8d6ddd01"
      url "https://github.com/meloniteai/melonite-client/releases/download/v#{version}/melonite_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "13b40e6633e806620b5e9b6e60a28486b4f764676d5ff5f0dd411bb155bd8e9f"
      url "https://github.com/meloniteai/melonite-client/releases/download/v#{version}/melonite_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4d0768967d2da904312ce61bd14615e85fbce523ba3e58ac8aeaa7c0a8edb3ea"
      url "https://github.com/meloniteai/melonite-client/releases/download/v#{version}/melonite_linux_arm64.tar.gz"
    end
  end

  name "melonite"
  desc "Melonite client: a headless MCP server for agent harnesses"
  homepage "https://melonite.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "melonite"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/melonite"]
    end
  end

  # No zap stanza required

end
